version: '3'

services:
  app:
    depends_on:
      - oracle
    build:
      context: ..
      dockerfile: config/dockerfile
    networks:
      - net


  oracle:
    image: wnameless/oracle-xe-11g-r2
    networks:
      - net

networks:
  net:
    driver: bridge